services:
  dphpc-cuda:
    image: paolo_custom/dphpc_cuda:24.04
    build:
      context: .
    shm_size: '32gb'
    hostname: dphpc.celati.com
    ports:
    - 23:22/tcp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    volumes:
    - ./../:/project
    - /var/run/docker.sock:/var/run/docker.sock
    - /storage/bulk2024b/dphpc_results:/storage/bulk2024b/dphpc_results
